services:
  vue-client:
    container_name: rummikub-buddy-client
    build:
      context: ./vue-client
      dockerfile: Dockerfile
    networks:
      - dev-env-network
    ports:
      - "8000:80"
    restart: always

networks:
  dev-env-network:
    external: true
