name: Deploy Rummikub Buddy Client

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build \
            -t rummikub_buddy_client:latest \
            -f laravel-client/Dockerfile \
            laravel-client

      - name: Stop old container
        run: docker rm -f rummikub_buddy_client || true

      - name: Run new container
        run: |
          docker run -d --restart=always \
            --name rummikub_buddy_client \
            --network appnet \
            -e APP_KEY="${{ secrets.CLIENT_APP_KEY }}" \
            -e APP_ENV=production \
            -e APP_DEBUG=false \
            -e APP_URL=https://rummikubbuddy.rasmusjensen.tech \
            -e API_BASE_ENDPOINT="${{ secrets.API_BASE_ENDPOINT }}" \
            -e X_API_KEY="${{ secrets.API_KEY }}" \
            -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            -e GOOGLE_REDIRECT_URI="${{ secrets.GOOGLE_REDIRECT_URI }}" \
            rummikub_buddy_client:latest

      - name: Prune old Docker images
        run: docker image prune -f
