name: Deploy Rummikub Buddy Api

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build \
            -t rummikub_buddy_api:latest \
            -f laravel-api/Dockerfile \
            laravel-api

      - name: Stop old container
        run: docker rm -f rummikub_buddy_api || true

      - name: Run new container
        run: |
          docker run -d --restart=always \
            --name rummikub_buddy_api \
            --network appnet \
            -e APP_KEY="${{ secrets.API_APP_KEY }}" \
            -e DB_CONNECTION=pgsql \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_DATABASE="${{ secrets.DB_DATABASE }}" \
            -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e API_KEY="${{ secrets.API_KEY }}" \
            -e APP_ENV=production \
            rummikub_buddy_api:latest

      - name: Run Migrations
        run: docker exec rummikub_buddy_api php artisan migrate --force

      - name: Prune old Docker images
        run: docker image prune -f
